# Generated by Django 4.0 on 2022-01-20 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_apply_job_job_alter_apply_job_jobappid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply_job',
            name='username',
            field=models.EmailField(default='', max_length=50),
        ),
    ]
