# Generated by Django 3.2.6 on 2022-01-23 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_apply_job_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apply_job',
            old_name='job',
            new_name='jobid',
        ),
    ]
