# Generated by Django 3.2.6 on 2022-01-24 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_job_apply_job_jobid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job_det',
            old_name='jobid',
            new_name='job',
        ),
    ]
