# Generated by Django 3.2.6 on 2022-01-24 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_jobid_job_det_job'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job_det',
            old_name='job',
            new_name='jobid',
        ),
    ]
