# Generated by Django 3.2.6 on 2022-01-24 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_job_job_det_jobid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apply_job',
            old_name='jobid',
            new_name='job',
        ),
    ]
