# Generated by Django 3.2.6 on 2022-01-24 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rename_jobid_apply_job_job'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apply_job',
            old_name='username',
            new_name='canemail',
        ),
    ]
