# Generated by Django 3.2.6 on 2022-01-24 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_rename_username_apply_job_canemail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apply_job',
            old_name='canemail',
            new_name='username',
        ),
    ]
