# Generated by Django 3.2.6 on 2022-01-24 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_rename_canemail_apply_job_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Com_job',
            fields=[
                ('comjob', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('username', models.EmailField(default='', max_length=50)),
                ('reason', models.CharField(max_length=900)),
                ('myjob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='com_applications', to='myapp.job_det')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicant', to='myapp.can_det')),
                ('userres', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicant_resume', to='myapp.resume')),
            ],
        ),
    ]
