# Generated by Django 3.2.6 on 2022-01-24 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_com_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply_job',
            name='comemail',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.com_det'),
        ),
    ]
