# Generated by Django 3.2.6 on 2022-01-24 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_remove_apply_job_comemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply_job',
            name='ename',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='apply_job',
            name='ephn',
            field=models.CharField(default='', max_length=10),
        ),
    ]
