# Generated by Django 3.2.6 on 2022-01-24 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_auto_20220125_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply_job',
            name='ephn',
            field=models.IntegerField(default=''),
        ),
    ]
