# Generated by Django 3.2.6 on 2022-01-24 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_apply_job_ephn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply_job',
            name='ephn',
            field=models.BigIntegerField(),
        ),
    ]
