# Generated by Django 3.2.6 on 2022-01-24 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_apply_job_comemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply_job',
            name='comemail',
            field=models.EmailField(max_length=254),
        ),
    ]
