# Generated by Django 3.2.6 on 2022-01-24 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_remove_apply_job_comemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply_job',
            name='comemail',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
