# Generated by Django 3.2.6 on 2022-01-24 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_apply_job_cemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='com_job',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
