# Generated by Django 3.2.6 on 2022-01-25 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_com_job_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply_job',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
