# Generated by Django 3.2.6 on 2022-01-25 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_apply_job_resume'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apply_job',
            old_name='resume',
            new_name='upload',
        ),
    ]
