# Generated by Django 3.2.6 on 2022-01-25 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_rename_resume_apply_job_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='can_det',
            name='epasswd',
        ),
        migrations.RemoveField(
            model_name='com_det',
            name='cpasswd',
        ),
        migrations.DeleteModel(
            name='Com_job',
        ),
    ]
