# Generated by Django 3.2.6 on 2022-02-07 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_auto_20220125_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='can_det',
            name='edob',
        ),
    ]
