# Generated by Django 3.2.6 on 2022-03-12 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_remove_can_det_edob'),
    ]

    operations = [
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('did', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('selected', models.BooleanField(default=False)),
                ('doi', models.CharField(max_length=20)),
                ('toi', models.CharField(max_length=20)),
                ('aoi', models.CharField(max_length=200)),
                ('loi', models.URLField()),
                ('candidate', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.apply_job')),
            ],
        ),
    ]
