# Generated by Django 3.2.6 on 2022-03-12 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_decision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decision',
            name='aoi',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='decision',
            name='doi',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='decision',
            name='loi',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='decision',
            name='toi',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
